# Generated by Django 3.0.6 on 2020-07-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homePageslides',
            fields=[
                ('slide_id', models.AutoField(primary_key=True, serialize=False)),
                ('slide_name', models.CharField(default='NA', max_length=20)),
                ('slide_img', models.ImageField(default='NA', upload_to='home/img')),
                ('slide_desc', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
