# Generated by Django 3.0.6 on 2020-07-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=20)),
                ('product_desc', models.CharField(default='', max_length=200)),
                ('product_price', models.ImageField(default=0, upload_to='')),
                ('product_img', models.ImageField(default='', upload_to='home/img')),
                ('category', models.CharField(default='', max_length=20)),
                ('sub_category', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='homepageslides',
            name='slide_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepageslides',
            name='slide_img',
            field=models.ImageField(default='', upload_to='home/img'),
        ),
        migrations.AlterField(
            model_name='homepageslides',
            name='slide_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
