# Generated by Django 3.0.6 on 2020-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200711_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestServingProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=20)),
                ('product_desc', models.CharField(default='', max_length=200)),
                ('date', models.DateField()),
                ('product_img', models.ImageField(default='', upload_to='home/img')),
                ('category', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
