# Generated by Django 3.0.6 on 2020-08-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20200822_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('prId', models.AutoField(primary_key=True, serialize=False)),
                ('prName', models.CharField(default='', max_length=30)),
                ('prDesc', models.CharField(default='', max_length=300)),
                ('prImg', models.ImageField(default='', upload_to='home/img')),
                ('prPrice', models.IntegerField(default=0)),
                ('prDate', models.DateField()),
                ('mainCat', models.CharField(default='', max_length=20)),
                ('featuredCat', models.CharField(default='', max_length=20)),
                ('onOfferCat', models.CharField(default='', max_length=20)),
                ('latestPrCat', models.CharField(default='', max_length=20)),
                ('topRatedPrCat', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
